# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       pjproject

# >> macros
# << macros

Summary:    A multimedia communication library implementing standard based protocols such as SIP, SDP, RTP, STUN, TURN, and ICE
Version:    2.11.1
Release:    1
Group:      Development/Libraries
License:    GPLv2
URL:        https://www.pjsip.org/
Source0:    %{name}-%{version}.tar.gz
Source100:  pjproject.yaml

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
# << files
